nextflow.enable.dsl=2

/* Common taxonomy path for jplace generated by either supported placer. */

process MakeGappaTaxonFile {
    container "${params.container__maliampi_tools}"
    label 'maliampi_tools'
    label 'io_limited'

    input:
    path leaf_info
    path taxonomy

    output:
    path 'gappa.taxon-file.tsv', emit: taxon_file

    script:
    """
    python3 - <<'PY'
    import csv

    ranks = ('superkingdom', 'phylum', 'class', 'order', 'family', 'genus', 'species')
    taxonomy = {row['tax_id']: row for row in csv.DictReader(open('${taxonomy}'))}
    with open('gappa.taxon-file.tsv', 'w', newline='') as out_h:
        writer = csv.writer(out_h, delimiter='\\t')
        for row in csv.DictReader(open('${leaf_info}')):
            taxon = taxonomy.get(row.get('tax_id'))
            if taxon is None:
                raise SystemExit(f"missing taxonomy for reference leaf {row.get('seqname')}")
            # Older taxtastic tables encode the biological superkingdom at
            # ``root__`` rather than a dedicated ``superkingdom`` column. Read
            # that existing lineage value; do not synthesize a taxon.
            superkingdom = taxon.get('superkingdom') or taxon.get('root__')
            lineage_ids = [superkingdom] + [taxon.get(rank) for rank in ranks[1:]]
            lineage = ';'.join(
                taxonomy[tax_id]['tax_name'] for tax_id in lineage_ids if tax_id
            )
            if not lineage:
                raise SystemExit(
                    f"reference leaf {row.get('seqname')} has no superkingdom taxonomy"
                )
            writer.writerow((row['seqname'], lineage))
    PY
    """
}

process GappaTaxonomy {
    container "${params.container__gappa}"
    label 'mem_veryhigh'
    errorStrategy 'ignore'

    input:
    path dedup_jplace
    path taxon_file

    output:
    path 'per_query.tsv', emit: per_query

    script:
    """
    set -e
    gappa examine assign --per-query-results --verbose --threads ${task.cpus} \\
      --jplace-path ${dedup_jplace} --taxon-file ${taxon_file}
    """
}

process ExtractGappaTaxonomy {
    container "${params.container__maliampi_tools}"
    label 'maliampi_tools'
    label 'io_mem'
    publishDir "${params.output}/taxonomy", mode: 'copy'

    input:
    path per_query
    path taxonomy
    path sv_h5ad

    output:
    path 'sv.taxonomy.parquet', emit: sv_taxonomy

    script:
    """
    python3 - <<'PY'
    import pandas as pd

    ranks = ('superkingdom', 'phylum', 'class', 'order', 'family', 'genus', 'species')
    rank_for_depth = {idx + 1: rank for idx, rank in enumerate(ranks)}
    taxonomy = pd.read_csv('${taxonomy}')
    name_to_id = dict(zip(taxonomy.tax_name, taxonomy.tax_id))
    assignments = pd.read_csv('${per_query}', sep='\\t')
    out = []
    if not assignments.empty:
        assignments = assignments[assignments.taxopath != 'DISTANT'].copy()
    for sv, sv_rows in assignments.groupby('name'):
        sv_rows['lineage'] = sv_rows.taxopath.map(lambda value: value.split(';'))
        sv_rows['rank_depth'] = sv_rows.lineage.map(len)
        last = {'rank': None, 'tax_name': None, 'ncbi_tax_id': None, 'lineage': None, 'afract': None}
        for depth, want_rank in rank_for_depth.items():
            candidates = sv_rows[sv_rows.rank_depth == depth]
            if not candidates.empty and candidates.afract.sum() > 0:
                names = sorted(set(candidates.lineage.map(lambda value: value[-1])))
                last = {
                    'rank': want_rank,
                    'tax_name': ' / '.join(names),
                    'ncbi_tax_id': ','.join(str(name_to_id.get(name, -1)) for name in names),
                    'lineage': ';'.join(candidates.lineage.iloc[0][:-1] + [' / '.join(names)]),
                    'afract': candidates.afract.sum(),
                }
            out.append({
                'sv': sv,
                'want_rank': want_rank,
                'rank': last['rank'],
                'rank_depth': depth,
                'tax_name': last['tax_name'],
                'ncbi_tax_id': last['ncbi_tax_id'],
                'lineage': last['lineage'],
                'afract': last['afract'],
                'ambiguous': len(candidates) != 1,
            })
    pd.DataFrame(out, columns=('sv', 'want_rank', 'rank', 'rank_depth', 'tax_name', 'ncbi_tax_id', 'lineage', 'afract', 'ambiguous')).to_csv('sv.taxonomy.external.csv', index=False)
    PY
    maliampi-taxonomy-mapping sv.taxonomy.external.csv sv.taxonomy.parquet --sv-h5ad ${sv_h5ad}
    """
}

process AggregateTaxonomyRank {
    container "${params.container__maliampi_tools}"
    label 'maliampi_tools'
    label 'io_mem'
    publishDir "${params.output}/taxonomy", mode: 'copy'

    input:
    tuple path(sv_h5ad), path(sv_taxonomy), val(rank), path(refpkg_identity), path(placement_identity)

    output:
    path "taxonomy.${rank}.h5ad", emit: abundance_h5ad

    script:
    """
    maliampi-taxonomy-aggregate ${sv_h5ad} ${sv_taxonomy} taxonomy.${rank}.h5ad \\
      --rank ${rank} --refpkg-identity ${refpkg_identity} --placement-identity ${placement_identity}
    """
}
