name: Test Maliampi

on: [push, pull_request]  

jobs:

  complete_workflow:
    runs-on: ubuntu-18.04
    env:
      NXF_ANSI_LOG: 0
    steps:
      - uses: actions/checkout@v1
      - name: Add openjdk
        run: |
          sudo update-java-alternatives -s adoptopenjdk-11-hotspot-amd64
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
      - name:  Run maliampi (full workflow)
        run: |
          nextflow run main.nf -with-docker ubuntu:18.04 -c nextflow.config.sample -profile testing --manifest maliampi-practice-data/autotest_manifest.csv --repo_fasta  maliampi-practice-data/test.repo.fasta --repo_si maliampi-practice-data/test.repo.seq_info.csv --taxdmp maliampi-practice-data/taxdmp.zip --email j-dev@golob.org --raxmlng_parsimony_trees 1 --raxmlng_random_trees 1 --output output  
      - name:  Verify output (DADA2)
        run: |
          [[ -s output/sv/dada2.specimen.sv.long.csv ]]
          [[ -s output/sv/dada2.sv.fasta ]]
          [[ -s output/sv/dada2.sv.map.csv ]]
          [[ -s output/sv/dada2.sv.weights.csv ]]
      - name:  Verify output (Refpkg)
        run: |
          [[ -s output/refpkg/refpkg.tar.gz ]]
      - name:  Verify output (placement)
        run: |
          [[ -s output/placement/dedup.jplace ]]
          [[ -s output/placement/adcl.csv.gz ]]
          [[ -s output/placement/edpl_list.csv ]]
          [[ -s output/placement/alpha_diversity.csv.gz ]]
          [[ -s output/placement/krd/krd_matrix.csv.gz ]]
      - name:  Verify output (classification)
        run: |
          [[ -s output/classify/sv_taxonomy.csv ]]
         

  dada2_workflow:
    runs-on: ubuntu-18.04
    env:
      NXF_ANSI_LOG: 0
    steps:
      - uses: actions/checkout@v1
      - name: Add openjdk
        run: |
          sudo apt-get update && sudo apt-get install -y openjdk-11-jdk-headless
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
      - name:  Run maliampi-dada2 (dada2 workflow)
        run: |
          nextflow run modules/dada2.nf -with-docker ubuntu:18.04 -c nextflow.config.sample -profile testing --manifest maliampi-practice-data/autotest_manifest.csv --output output
      - name:  Verify output
        run: |
          [[ -s output/sv/dada2.specimen.sv.long.csv ]]
          [[ -s output/sv/dada2.sv.fasta ]]
          [[ -s output/sv/dada2.sv.map.csv ]]
          [[ -s output/sv/dada2.sv.weights.csv ]]

  
  refpkg_workflow:
    runs-on: ubuntu-18.04
    env:
      NXF_ANSI_LOG: 0
    steps:
      - uses: actions/checkout@v1
      - name: Add openjdk
        run: |
          sudo apt-get update && sudo apt-get install -y openjdk-11-jdk-headless
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
      - name:  Run maliampi-refpkg (Reference Package Workflow)
        run: |
          nextflow run modules/refpackage.nf -with-docker ubuntu:18.04 -c nextflow.config.sample -profile testing --raxmlng_parsimony_trees 1 --raxmlng_random_trees 1 --sv_fasta tests/sv/dada2.sv.fasta --repo_fasta  maliampi-practice-data/test.repo.fasta  --repo_si maliampi-practice-data/test.repo.seq_info.csv --taxdmp maliampi-practice-data/taxdmp.zip --email j-dev@golob.org --output output
      - name:  Verify output
        run: |
          [[ -s output/refpkg/refpkg.tar.gz ]]

  pplacer_place_classify_workflow:
    runs-on: ubuntu-18.04
    env:
      NXF_ANSI_LOG: 0
    steps:
      - uses: actions/checkout@v1
      - name: Add openjdk
        run: |
          sudo apt-get update && sudo apt-get install -y openjdk-11-jdk-headless  
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
      - name:  Run maliampi-pplacer (placement and classification)
        run: |
          nextflow run modules/pplacer_place_classify.nf -with-docker ubuntu:18.04 -c nextflow.config.sample -profile testing --sv_fasta tests/sv/dada2.sv.fasta --weights tests/sv/dada2.sv.weights.csv --map tests/sv/dada2.sv.map.csv  --refpkg tests/refpkg/refpkg.tar.gz --output output
      - name:  Verify output (placement)
        run: |
          [[ -s output/placement/dedup.jplace ]]
          [[ -s output/placement/redup.jplace.gz ]]
          [[ -s output/placement/adcl.csv.gz ]]
          [[ -s output/placement/edpl.csv.gz ]]
          [[ -s output/placement/alpha_diversity.csv.gz ]]
          [[ -s output/placement/kr_distance.csv.gz ]]
      - name:  Verify output (classification)
        run: |
          [[ -s output/classify/sv_taxonomy.csv ]]

  epang_place_classify_weights_map_workflow:
    runs-on: ubuntu-18.04
    env:
      NXF_ANSI_LOG: 0
    steps:
      - uses: actions/checkout@v1
      - name: Add openjdk
        run: |
          sudo apt-get update && sudo apt-get install -y openjdk-11-jdk-headless
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h          
      - name:  Run maliampi-epang (placement and classification)
        run: |
          nextflow run modules/epang_place_classify.nf -with-docker ubuntu:18.04 -c nextflow.config.sample -profile testing --weights tests/sv/dada2.sv.weights.csv --map tests/sv/dada2.sv.map.csv --sv_fasta tests/sv/dada2.sv.fasta  --refpkg tests/refpkg/refpkg.tar.gz --output output
      - name:  Verify output (placement and classify / weight and map)
        run: |
          [[ -s output/placement/dedup.jplace ]]
          [[ -s output/placement/adcl.csv.gz ]]
          [[ -s output/placement/edpl_list.csv ]]
          [[ -s output/placement/alpha_diversity.csv.gz ]]
          [[ -s output/placement/krd/krd_matrix.csv.gz ]]
          [[ -s output/classify/sv_taxonomy.csv ]]  
  
  epang_place_classify_seqtable_workflow:
    runs-on: ubuntu-18.04
    env:
      NXF_ANSI_LOG: 0
    steps:
      - uses: actions/checkout@v1
      - name: Add openjdk
        run: |
          sudo apt-get update && sudo apt-get install -y openjdk-11-jdk-headless
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h          
      - name:  Run maliampi-epang-seqtable (placement and classification)
        run: |
          nextflow run modules/epang_place_classify.nf -with-docker ubuntu:18.04 -c nextflow.config.sample -profile testing --seqtable tests/sv/dada2.combined.seqtabs.nochimera.csv  --refpkg tests/refpkg/refpkg.tar.gz --output output_seqtable
      - name:  Verify output (placement and classify / seqtable)
        run: |
          [[ -s output_seqtable/placement/dedup.jplace ]]
          [[ -s output_seqtable/placement/adcl.csv.gz ]]
          [[ -s output_seqtable/placement/edpl_list.csv ]]
          [[ -s output_seqtable/placement/alpha_diversity.csv.gz ]]
          [[ -s output_seqtable/placement/krd/krd_matrix.csv.gz ]]
          [[ -s output_seqtable/classify/sv_taxonomy.csv ]]   

  epang_place_classify_sharetable_workflow:
    runs-on: ubuntu-18.04
    env:
      NXF_ANSI_LOG: 0
    steps:
      - uses: actions/checkout@v1
      - name: Add openjdk
        run: |
          sudo apt-get update && sudo apt-get install -y openjdk-11-jdk-headless
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h          
      - name:  Run maliampi-epang-sharetable (placement and classification)
        run: |
          nextflow run modules/epang_place_classify.nf -with-docker ubuntu:18.04 -c nextflow.config.sample -profile testing --sharetable tests/sv/dada2.sv.shared.txt --sv_fasta tests/sv/dada2.sv.fasta  --refpkg tests/refpkg/refpkg.tar.gz --output output_sharetable
      - name:  Verify output (placement and classify / sharetable)
        run: |
          [[ -s output_sharetable/placement/dedup.jplace ]]
          [[ -s output_sharetable/placement/adcl.csv.gz ]]
          [[ -s output_sharetable/placement/edpl_list.csv ]]
          [[ -s output_sharetable/placement/alpha_diversity.csv.gz ]]
          [[ -s output_sharetable/placement/krd/krd_matrix.csv.gz ]]
          [[ -s output_sharetable/classify/sv_taxonomy.csv ]]  
          